### PR TITLE
add 'Not sufficient funds' message for customer

### PR DESCRIPTION
**Pull request by AllanQ**

### CODE REVIEW

**Comment by AllanQ** [comment]
Платеж отклонен банком, выпустившим вашу карту. Недостаточно средств для оплаты

The payment has been declined by your bank. There is not sufficient funds remaining to pay

Need to translate to
da de es fi fr it ja no pl sv tr zh

**Comment by AllanQ** [comment]
:up:

**Comment by avsh** [comment]
@AllanQ upgrade version of gem

**Comment by AllanQ** [comment]
:up:

**Pull request merged**
